version: '3.7'
services:
  kimebenziyo:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
      - ./docker/db_init/database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/db_init/tables.sql:/docker-entrypoint-initdb.d/2.sql